language: csharp
dist: trusty
install:
  - nuget restore TicTacToe1.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Debug TicTacToe1.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./TicTacToe1.Tests/bin/Debug/TicTacToe1.Tests.dll
