language: csharp
dist: trusty
install:
  - nuget restore TicTacToe1.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Debug TicTacToe1.sln
